// "use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MobileNav from "@/components/MobileNav";
import Nav from "@/components/Nav";
// import { usePathname } from 'next/navigation'
const inter = Inter({ subsets: ["latin"] });
// const currenr = usePathname();

export const metadata: Metadata = {
  title: "Mlrit",
  description: "Generated by create next app",
};
const crt2 = [
  { n: "2.1" },
  { n: "2.2" },
  { n: "2.3" },
  { n: "2.4" },
  { n: "2.5" },
  { n: "2.6" },
  { n: "2.7" },
];
const crt3 = ["3.1", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7"];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full h-[100px] fixed top-0 flex flex-row  bg-[#dcf3da] ">
          <img src="/mlrit.jpeg" alt="mlrit" className="h-[100px]" />
          <div className="flex flex-row justify-center w-full">
            <img src="https://mlritnaac.web.app/images/header_cut.png" alt="" />
          </div>
        </header>
        <div className="flex flex-row w-full">
          <MobileNav />
          <Nav/>
          {children}
        </div>
      </body>
    </html>
  );
}
